### ISSUE TITLE
Keep loaded tab after group switching

### ISSUE THREAD

**Issue by christian-momon** [Drive4ik/simple-tab-groups#146] opened 2018-04-19 14:15 UTC
A loaded tab does not stay loaded after you switch to another group tab and come back to the first group tab. The tab reload on switching, it is a huge issue for smart usage.

Currently steps: 
- select a group tab (G1)
- load a tab (G1:T1) in this group
- switch to another group tab
- switch again to the first group (G1)
- select the tab of the start (G1:T1)
- the tab (G1:T1) is reloaded.

It would be greater that the last step displays the tab previously loaded than reload it. When you switch group very often, it is horrible to reload again tab  previously loaded.

More memory used? Yes, but it doesn't matter because it would be very useful.

SimpleTabGroups in really great. But I won't use it without this feature.

**Comment by Drive4ik** [comment] 2018-04-30 11:12
Thanks @Keith94 
Closed as duplicate of #2

**Closed by Drive4ik** 2018-04-30 11:12 UTC
