### ISSUE TITLE
Sync group settings

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#636] opened 2020-06-16 17:50 UTC
**Is your feature request related to a problem? Please describe.**
You have implemented a way to "sync" groups through bookmarks, and that system works well. However, I find that I'm frequently trying to sync group settings between devices as well. I have long lists of regular expressions, for example, and it would be nice to export/import these.

**Describe the solution you'd like**
It would be great to have group export include a bookmark that, when opened, could be used by the extension to update a group's settings to match those from the device that created the bookmark. Alternatively, you could provide an import / export option per-group via files that we could transfer ourselves.

**Describe alternatives you've considered**
The only alternative I can think of is to look at both devices, or take notes or screenshots to ensure all the settings match.

**Additional context**
Please do not mix this with syncing overall extension settings. It's nice not to require syncing of all settings. In particular, I keep the backup folder settings different, so bookmark sync doesn't overwrite groups from different devices, but rather each device gets its own bookmark folder for groups backup.

**Comment by 7wells** [comment] 2020-06-18 16:57
uBlock origin has a (Firefox) sync function, and to my understanding, still different Firefoxes (or Chrome?) on different devices can have different uBlock settings. There is a function to download, to upload, and to merge uBlock settings via Firefox Sync - and this is possible for different settings tabs individually, e.g. filters, whitelists, etc. So in the end, the user can decide, which parts of the settings of uBlock should be synced and aligned to other devices (via Firefox Sync) and which ones should be kept device/browser-specific.

As I am no coding expert, I have difficulties to find the spot in the code of uBlock origin, but maybe somebody from the developers/expert contributors here would like to have a look?

https://github.com/gorhill/uBlock

Please accept my apologies if my comment here is maybe not adequate or in the wrong spot. I am willing to learn. Thank you. :)

**Comment by ejm554** [comment] 2020-08-31 17:12
Is this issue a Duplicate of #628 ?

**Comment by bonnepioche** [comment] 2020-09-17 18:18
Hi, I would LOVE to have syncing the tabs accross devices as well. And yes, this feature request is a duplicate of #628 (the way I understand it).

**Comment by Drive4ik** [comment] 2020-10-07 15:22
And also duplicate #291 
At the moment, I'm looking for a way out, how to make synchronization of tabs and settings convenient for all users. So far, this is limited by the size of the data being synced. Read more #291

**Closed by Drive4ik** 2020-10-07 15:22 UTC
