### ISSUE TITLE
Multiple Computers

### ISSUE THREAD

**Issue by efeyitim** [Drive4ik/simple-tab-groups#796] opened 2021-03-25 05:46 UTC
Hello,

I want to share my tabs between the computer at home and computer at work. I want to see the same tab groups and the same tabs at both computers. Firefox account is logged and sync is on. Is there a way to do that?

**Comment by KleinByte** [comment] 2021-03-28 19:59
Not connected to the project, but there is kind of a way to do this. There is no real-time syncing. But you can go into the STG (Simple Tab Group )settings and there are options for creating automatic backups. This puts a folder in your Downloads folder _Firefox only has access to your downloads folder for obvious security/privacy reasons_ . In that folder, STG will automatically place a file that you can then use to restore on another computer.

I see you are brand new to CS, so maybe this could be a nice little problem to work on automating sending that file to another pc with a script.

The alternative route is to have STG also save groups into your bookmark folder, Then you can navigate to that bookmark folder in Firefox, right click and "Open Bookmark in Group" and select the group its for. Voiala , all tabs are back.

Maybe the dev will implement an automatic syncing service, but that would be alot of work most likely, as STG obviously shouldn't have access to pull files from your pc and send them to another. So the Dev would have to maintain a centralized server that stores everyone's backups.  Which then starts falling into major security and privacy conserns and that is a whole engineering feat of itself.

Prob stick to the first or second option!
Thanks, hope that helps.

**Comment by valsamis-d** [comment] 2021-03-29 08:00
> I'm Not connected to the project, but there is kind of a way to do this. There is no real-time syncing. But you can go into the STG (Simple Tab Group )settings and there are options for creating automatic backups. This puts a folder in your Downloads folder _Firefox only has access to your downloads folder for obvious security/privacy reasons_ . In that folder, STG will automatically place a file that you can then use to restore on another computer.
> 
> 
> 
> I see you are brand new to CS, so maybe this could be a nice little problem to work on automating sending that file to another pc with a script.
> 
> 
> 
> The alternative route is to have STG also save groups into your bookmark folder, Then you can navigate to that bookmark folder in Firefox, right click and "Open Bookmark in Group" and select the group its for. Voiala , all tabs are back.
> 
> 
> 
> Maybe the dev will implement an automatic syncing service, but that would be alot of work most likely, as STG obviously shouldn't have access to pull files from your pc and send them to another. So the Dev would have to maintain a centralized server that stores everyone's backups.  Which then starts falling into major security and privacy conserns and that is a whole engineering feat of itself.
> 
> 
> 
> Prob stick to the first or second option!
> 
> Thanks, hope that helps.

Your idea of transferring backups made me take advantage of Windows links and Google Drive. So, I made a directory link from "%USERNAME%\Downloads\_<STG_Backup_Directory>_" to a Google Drive folder.

**Comment by nekohayo** [comment] 2021-04-21 04:33
This is essentially a duplicate of issue #291 (which seems to be technically impossible for now), and as such I would suggest you close your ticket in favor of 291 and to keep the issues tracker cleaner for the maintainer.

**Comment by julie777** [comment] 2022-01-23 17:18
I just submitted a new enhancement request for changing the group definitions to use bookmarks as their storage mechanism. #911

I believe this would support multiple computer synchronization by just turning on Firefox bookmark sync.

**Comment by Drive4ik** [comment] 2023-04-22 15:30
Duplicate of #291

**Closed by Drive4ik** 2023-04-22 15:30 UTC
