### ISSUE TITLE
Nested groups

### ISSUE THREAD

**Issue by Fictitious-Rotor** [Drive4ik/simple-tab-groups#594] opened 2020-04-24 21:55 UTC
I'm stricken by the disease of leaving tabs open and this tool has been an enabler for me.
As my condition worsens my demand for more grouping grows ever stronger.

I'd like the ability to nest groups within one another so that I can create subcategories (yes it really is getting that bad).

If you're short on time I'd be happy to put something together and submit a pull request, if you're accepting those.

Presently I just use the flat grouping system with prefixes, but a nesting system would be much appreciated.

**Comment by ThangaAyyanar** [comment] 2020-04-28 10:40
Similar to #586

**Comment by Drive4ik** [comment] 2020-05-05 17:55
Duplicate of #302

The time will come, and I will do it)
I’ll have to redo a lot, there are a lot of bugs with one level ... I'm afraid to imagine what will happen with a lot of nesting ...

**Closed by Drive4ik** 2020-05-05 17:55 UTC

**Comment by grahamperrin** [comment] 2021-02-28 20:32
> … I'm afraid to imagine what will happen with a lot of nesting ...

Justifiably cautious. [With great power comes great complexity](https://github.com/piroor/treestyletab/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc).
