### ISSUE TITLE
The Addon was disabled suddenly by Firefox and is not supported anymore.  Is there a way to pass that and enable the plugin?

### ISSUE THREAD

**Issue by devedelie** [Drive4ik/simple-tab-groups#386] opened 2019-05-04 16:29 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows]
 - Firefox version: [e.g. 63]
 - Simple Tab Groups version: [e.g. 3.0.8]

**Additional context**

**Comment by sleepindawg** [comment] 2019-05-04 19:08
I'm also having the same problem. Being on Linux I often take risks with where I browse, and I was thinking that I may have broke either the addon, or Firefox here on my machine. I started looking for other options but none of them would even seem to download much less install so I decided to look for other possible causes for the problem.

Sorry I don't have anything to offer as help for the problem.

**Comment by bartkamphorst** [comment] 2019-05-04 19:58
@devedelie @sleepindawg This appears to be caused by a [Firefox issue](https://www.ghacks.net/2019/05/04/your-firefox-extensions-are-all-disabled-thats-a-bug/). I think Mozilla will come up with a fix for this quickly.

**Comment by markx100x** [comment] 2019-05-05 00:03
As according to Mozilla this is related to unsigned extensions, I hope Drive4ik signs the extension as soon as possible! 
In the meantime I have loaded Firefox Developer Edition as a workaround, and enabled unsigned extensions. 
However, I am having trouble loading my existing simple tab groups from Firefox into the simple tab groups for Firefox Developer Edition. In the past I have messed around with session.js, but possibly now Simple Tab Groups stores its data in Sqlite database file?
Any help appreciated in loading existing simple tab groups into Firefox Developer Edition!
And of course I hope Drive4ik signs this very important extension!

**Comment by Tyrewt** [comment] 2019-05-05 00:26
I too just started experiencing this in Firefox 66.0.3 under Ubuntu 18.04.

Firefox extension is showing: "Simple Tab Groups could not be verified for use in Firefox and has been disabled."

**Comment by sleepindawg** [comment] 2019-05-05 02:46
Actually all of that class of addon has hit the same wall for me, the other class of addon that I have is fine.

**Comment by devedelie** [comment] 2019-05-05 08:48
I tried the developers edition of firefox and also tried to set "xpinstall.signatures.required" to false, but non of the solutions helped me. I hope Drive4ik will solve it soon.

I found a working addon named "workspaces" which does the same thing, but in terms of efficiency, it is not RAM friendly addon, because it loads all the tabs at the same time while I open a category. (So if I have 100 tabs, it will load their content all at once).

**Comment by deanforrester** [comment] 2019-05-05 10:21
I am having the same issue since last night, due to the FF bug.  

Until the problem is solved, could someone please help me on where does STG stores the URLs of tabs?

Thanks, Dean

**Comment by devedelie** [comment] 2019-05-05 10:51
My default STG (Windows OS) are in downloads--> STG-backups.  Probably yours as well

**Comment by deanforrester** [comment] 2019-05-05 13:28
Thank you, indeed backups are there but their dates are random, with a gap of 5-10 days inbetween, which cannot be correct as I am using STG every day. Shouldn't there be a list stored somewhere with the last urls and tab groups used?

**Comment by markx100x** [comment] 2019-05-05 21:10
Seems to be resolved now with Firefox Quantum version 66.0.4.
Either Drive4ik (modified the code and) signed the extension 
or Mozilla changed their policy regarding signing.
If the former, THANK YOU!
And I was just researching how to install older versions of Firefox and preventing auto updating,
just as I did when Mozilla first killed Panorama.
Thanks again!

**Comment by sleepindawg** [comment] 2019-05-06 11:49
@markx100x 

Do you have a windows machine or something else?

**Comment by devedelie** [comment] 2019-05-06 15:04
Same here @markx100x  , I think it was fixed (either Mozilla or Drive4ik)
Back to normal (-:

**Comment by bartkamphorst** [comment] 2019-05-06 15:47
> I think it was fixed (either Mozilla or Drive4ik)

It was a bug fix by Mozilla, see [here](https://www.ghacks.net/2019/05/05/firefox-66-0-4-with-add-on-signing-fix-release-on-its-way/). Updating to Firefox 66.0.4 should resolve the issue, though it might be necessary to manually disable and re-enable the add-on after updating Firefox to restore the simple-tab-groups icon (this was my experience anyway).

**Closed** 2019-05-06 17:13 UTC
