### ISSUE TITLE
closing the browser doesn't seem to save the current tabs in the group?

### ISSUE THREAD

**Issue by xerance** [Drive4ik/simple-tab-groups#165] opened 2018-05-29 17:05 UTC
Hello, testing around with different tab group extensions. It seems like the current group I have open doesn't save the tabs in the currently active open session while closing the browser. 

Is this intended? Do i have to swap group or close it before closing the actually browser?

browser version firefox quantum 60

edit: seems like it requiers "Show your windows and tabs from last time". Is there any workaround this, would rather like a specific site or group to open up upon start, not necessary the one that was open when I closed the browser.

**Comment by xerance** [comment] 2018-05-29 17:49
Welp, thanks for the fast reply.
Guess there isn't any plans on adding a "set startup group option"?

**Comment by Jaxx005** [comment] 2018-05-30 20:18
Hi: I am also getting this now.  

Info:
Version 60.0.1 (64-bit) 
I have "Show your window sna d tabs from last time" checked (and works)

FF is closed (and I shutdown the PC etc.)... 
Next time FF is opened it has:
- all previous tabs opened  (but no longer associated with a tab group - see below)...
- "default icon" tab group shown (should be the icon matching the current tabs)
    (of course, if this goes unnoticed, the tab group goes out of sync)
- opening a Tab Group replaces all the 'non-grouped' tabs (by design)

Note: there may have been a second FF window, which possibly has been 'grabbed' by Simple Tab Groups' before the original FF window (with all the tabs in it).  Closing the second (single-tab) window first, might be disconnecting the tab groups?)

This "Orphaned tabs" issue was a problem before (and might still be listed elsewhere?) but this appears to be occuring more often now?

I will retest and update this if different.

Regards/

**Comment by Drive4ik** [comment] 2018-06-27 14:24
Pease retest it on STG 3.0 and FF 61

**Closed by Drive4ik** 2018-06-27 14:24 UTC
