### ISSUE TITLE
Cloud Sync

### ISSUE THREAD

**Issue by zabarocky** [Drive4ik/simple-tab-groups#1033] opened 2023-04-21 18:01 UTC
**Is your feature request related to a problem? Please describe.**
I don't like not having my groups when switching from desktop to laptop, and instead having to download my backup and transfer it to my other device.

**Describe the solution you'd like**
A feature to sync the groups to a cloud of some sorts, maybe the same way firefox profiles work, where your extensions and bookmarks are auto-downloaded upon a new install of FF and signing in?

**Describe alternatives you've considered**
I've thought about using one drive to "cloud sync" the backup, but seeing as you can't choose an individual folder outside of the 3 normal folders, I'm having to manually upload and download the backup when I switch devices.

**Comment by Drive4ik** [comment] 2023-04-22 15:30
Duplicate of #291

**Closed by Drive4ik** 2023-04-22 15:30 UTC
