### ISSUE TITLE
Tabs "voided" randomly

### ISSUE THREAD

**Issue by Intenditore** [Drive4ik/simple-tab-groups#568] opened 2020-03-23 19:50 UTC
Problem: some tabs (opened long ago) get "voided" - they loose all the history and the address so it's impossible to restore them. The cause is uncertain, usually it happens after the restart 

FF 74.0

**Comment by Drive4ik** [comment] 2020-03-23 20:04
Duplicate of #569

**Closed by Drive4ik** 2020-03-23 20:04 UTC
