### ISSUE TITLE
Enable use of sub-groups

### ISSUE THREAD

**Issue by Stetto** [Drive4ik/simple-tab-groups#651] opened 2020-07-11 10:16 UTC
Hi, 

i have some groups like a "Shopping List" for a smartwatch, washing maschine, LED bulbs, motorcycle .. 
i want to group this in a supergroup. 

and i have some groups for excel/VB, contao, web design and so forth and want to groups this groups as a super group "programming" or something like that.

is that possible or will be? can't find existing issues or features.

**Comment by gkaklas** [comment] 2020-07-11 11:42
I believe this is a duplicate of #302 :thinking:

**Comment by Stetto** [comment] 2020-07-11 13:31
oh yes, i think so. and #535 

don't know why i didn't find those tickets earlier.

unlovely to read, that it is nearly impossible and so hard work :-/ 

thanks

**Comment by gkaklas** [comment] 2020-07-11 13:38
Then you can close this issue! :)

**Comment by jdevoldere** [comment] 2020-07-27 09:25
I have several groups that have 100+ tabs. Sub-groups would really make life easier.

**Closed** 2020-10-08 14:46 UTC
