### ISSUE TITLE
Optimized Version

### ISSUE THREAD

**Issue by Hirnsausen** [Drive4ik/simple-tab-groups#841] opened 2021-07-14 04:36 UTC
Hi Drive4K,

your plugin "Simple Tab Groups" is quite useful for mass media persons like me, who need to keep hundreds of tabs open and to have them organized in thematic groups.

I want to make a suggestion: can you create a second version of your tab manager plugin, that offers an additional line of tabs above the existing line of tabs? That new, upper line of tabs would actually be the tab groups. Depending on which tab group is activated, the list of the tabs inside the second row would change.

Each group tab can have its own color and name, and drag'n'drop between groups is possible.

A design like this lets us avoid having to open an own screen just to see all groups and to change the active group.

Optionally, the tab row with all website tabs could be lower in height, as it was some versions of Firefox before, but the group tabs (upper row) should indeed be low in height - to save vertical space and also to create a distinctive design for the color-enabled group tabs and regular website tabs (unless the user has chosen a lower height for the website tabs, too).

In fact, just a few years ago, there was such a plugin, but the sad story is that the developer died, the code was not on GitHub, and eventually that amazing plugin became incompatible with the newer versions of Firefox. People like me (news mass media) who need to keep hundreds of tabs open, are missing that plugin badly. Please, consider. Since that former plugin was quite famous, a new similar plugin like that would automatically raise into the hall of fame among us special users, too.

Best wishes, stay safe and healthy,

Sven

**Comment by Newbiez** [comment] 2021-07-18 08:12
Duplicate of #739

**Comment by Drive4ik** [comment] 2021-08-03 13:23
Yes, duplicate, and also read this https://github.com/Drive4ik/simple-tab-groups/issues/739#issuecomment-891842870

**Closed by Drive4ik** 2021-08-03 13:23 UTC
