### ISSUE TITLE
Unsynchronized tabs when tab are open before STG is fully loaded

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#278] opened 2018-10-28 15:52 UTC
**Describe the bug**
If you open new tab when Firefox is launching but the addon is not yet ready, those tab are then hidden and not added in the current group.

This append a lot when I just quickly open my browser to do a quick search and the last used group will open.

```
Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:
Move all of these tabs into current group/window
Create new group with all of these tabs
Close all of these tabs
```

**To Reproduce**
1. Close firefox
2. Open Firefox
3. Open a tab as soon as you can
4. Wait for the addon to load
4. The tab is hidden and is unsynchronized

**Expected behavior**
The tab should be loaded in the current group.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14

**Comment by Drive4ik** [comment] 2018-10-29 11:12
Duplicate of #274

**Closed by Drive4ik** 2018-10-29 11:12 UTC
