### ISSUE TITLE
2019-01-22: Error. UnknownError - The operation failed for reason unrelated to the database itself ... 

### ISSUE THREAD

**Issue by Hirnsausen** [Drive4ik/simple-tab-groups#316] opened 2019-01-22 23:29 UTC
**Describe the bug**
I get a yellow warning triangle instead of the regular symbol, and I cannot access any of the groups therefore. All tabs of all former groups are now again displayed in one long line.

**To Reproduce**
No idea how to reproduce. maybe the latest update of Firefox Nightly causes this issue. It happens right with the start of FFN.

**Expected behavior**
To see the regular symbol, and to be able to access all my groups.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16428907/51572417-5ead5180-1e73-11e9-8077-b909fc06aac1.png)

**Desktop (please complete the following information):**
 - Windows Home Premium 64bit
 - Firefox Nightly 66. ...
 - Can't access, but should be ther latest version

**Additional context**
I also want a pizza pepperoni with a lot of cheese and green olives.

**Comment by nhua6456** [comment] 2019-01-23 11:02
I too have a similar issue using the latest nightly. A new STG (3.3.5 commit d7cf0a5a6d642966927c26acb6418c4ca9b4eeaa ) install seems to work fine, but restoring my last known working backup leads to a yellow symbol with the following error message.
![STG error](http://vigne.fgghjjkll.net/~fgghjjkll/Screenshot%20(18).png)
This error does not occur on the stable branch of Firefox 64 and STG 3.3.4.

**Comment by Drive4ik** [comment] 2019-01-23 11:46
duplicate of #283

**Comment by Drive4ik** [comment] 2019-01-23 11:49
These URLs `resourse://...` or `chrome://extensions/...` are not addon. This is components of unstable Firefox...

**Comment by Drive4ik** [comment] 2019-01-23 11:51
You need to create issue with this screenshot on https://bugzilla.mozilla.org/

**Closed** 2019-01-23 15:19 UTC
Labels: duplicate

**Comment by Drive4ik** [comment] 2019-03-13 10:55
Can you retest this issue with latest STG? (3.4.2.1 or higher)

**Comment by Hirnsausen** [comment] 2019-03-16 02:04
Okay. That particular problem seems to be solved. :-)
Thanks.

What was causing that problem?

**Comment by Drive4ik** [comment] 2019-03-25 12:00
@Hirnsausen Maybe this
> Starting in release 66, extensions use IndexedDB as the backend for local storage instead of a JSON file.

https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/
