### ISSUE TITLE
STG 4.2 Popup Search bar does not autofocus after pressing F8

### ISSUE THREAD

**Issue by iDuck12** [Drive4ik/simple-tab-groups#481] opened 2019-10-21 21:20 UTC
**Describe the bug**
After STG 4.2 update, Search bar no longer auto-focuses after pressing popup hotkey F8.

**To Reproduce**
1. Update to latest STG version 4.2
2. Press F8

**Expected behavior**
Before STG 4.2 update the user could press F8 and begin typing into the Search field to quickly find an open tap.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox version 69.0.3 (64-bit)
 - Simple Tab Groups version 4.2

**Additional context**

**Comment by falolaf** [comment] 2019-10-22 05:08
I can confirm this. Most annoying indeed!

**Comment by Drive4ik** [comment] 2019-10-22 14:10
Duplicate of #480

**Closed by Drive4ik** 2019-10-22 14:10 UTC
