### ISSUE TITLE
No way to ungroup tabs?

### ISSUE THREAD

**Issue by shield72** [Drive4ik/simple-tab-groups#809] opened 2021-05-02 16:46 UTC
Hello all,

I'm new to Simple Tab Groups, which in my understanding works as a visual filter, hiding anything which is not part of the active group.  Now, after quite some testing, I'm unable to find a way to unassign a tab to a group.  Tabs which are not assigned to a group do reappear when the active group becomes unloaded - but how can I throw a grouped tab (or a whole group at once) back into this pool of unassigned tabs?

**Comment by JoshCode94** [comment] 2021-05-03 18:20
I just had a look and it seems you're right. The Discard tab option simply unloads the selected tab(s). No option to actually un-assign. So it part of your workflow using the un-assigned tabs as their own group?? Why not just create a group called un-assigned? I know it's not what you're looking for but it might be the only option as this addon looks dead at present haha

**Comment by nekohayo** [comment] 2021-06-03 03:10
There isn't such a thing as a "no groups" group in STG that you can move things _to_, that I know of... only a state of tags erronously not belonging to any group (usually due to some rare bugs).

I have a group that I called "general" for the purpose of moving stuff that "doesn't fit into anything else". Personally I think that's the expected behavior (otherwise you'll probably get people complaining about a permanent un-deleteable general group...), and would therefore suggest closing this ticket as an answered question.

**Comment by shield72** [comment] 2021-06-07 06:13
Thank you both for your response.

Let me explain the reason for asking. I am usually having 4 browser windows open which are categorized (private stuff, work, coding, and anything else). Since each windows holds several sequenced "groups" of related tabs, it's still a mess. STG would allow me to have only a single windows open that shows only the group that is currently relevant.

... but in case I quit using STG, I would like to reconstruct the previous 4-windows-state. In order to do so I would need to unload the groups first, one by one into the window they belong to. But that's not possible, right?

**Comment by nekohayo** [comment] 2021-06-07 13:30
Apparently STG "Now fully supports multiple windows", which is not something I would have expected. Indeed when you right-click a tab group, there is a "Open group in new window" menu item. I presume you maybe just need to ensure to shutdown Firefox globally (not one window at a time) with Ctrl+Q or something like that? (I'm just guessing). And I have no idea how/if it's possible to "merge" a group from a separate window back into the main window...

**Comment by julie777** [comment] 2021-08-20 16:21
It seems like having each tag group stored as a bookmark folder would make it easy to quit using STG and then open each bookmark folder in a separate window.

**Comment by Drive4ik** [comment] 2021-11-19 17:25
If someone needs to make tabs outside the group, just open a new browser window, it will be without the group if you do not have the appropriate option in the addon settings, and just drag the necessary tabs in this new window. These tabs will be detached from the group

**Closed by Drive4ik** 2021-11-19 17:25 UTC
