### ISSUE TITLE
Add user options for group column count and size.

### ISSUE THREAD

**Issue by Teslafly** [Drive4ik/simple-tab-groups#639] opened 2020-06-22 04:44 UTC
**Is your feature request related to a problem? Please describe.**
while single tab groups is the best replacement i've found for the original tab groups, it becomes increasingly clumbersome to manage everything as you add more groups. This is because the group representations take up a large amount of space and scrolling and moving tabs between 20+ groups starts to get tedious. 

**Describe the solution you'd like**
The ideal solution to this would be to implement the original "simple view"( issue #88 ) as it had great group density and availability. 
A stop gap measure and purpose if this issue is to add user adjustable column and group height to increase the density of groups. for example, from the default 3 columns and 2/3 page length groups, I would want 4 columns and 1/4 page length groups. (probably measure in pixels)

**Describe alternatives you've considered**
At the root of it, having the ability to increase group density and move tabs between the first and last group in 30+ groups without scrolling would be great. shrinking the group size would help, but a view like "simple groups" would help the most.

**Comment by Teslafly** [comment] 2020-06-22 05:50
I missed this when searching earlier, related to #362

**Comment by Drive4ik** [comment] 2020-10-08 16:11
Duplicate of #362
Perhaps I will do it in the future, if there is more time

**Closed by Drive4ik** 2020-10-08 16:11 UTC
