### ISSUE TITLE
All groups emptied once closed all windows

### ISSUE THREAD

**Issue by m-colombo** [Drive4ik/simple-tab-groups#434] opened 2019-08-09 10:47 UTC
**Describe the bug**
If I close all windows, but not  the application (is MacOS it's possible), when I open a new window all the groups contains no tabs.

**To Reproduce**
1- Open a group
2- close all firefox windows (clicking on red dot)
3- open a new window (cmd+n)

**Desktop (please complete the following information):**
 - OS and version: Mac OS 10.14.5 
 - Firefox version: 68.0.1
 - Simple Tab Groups version: 4.0.0.2

**Comment by Reiseend** [comment] 2019-08-09 15:59
Hi I have the same issue since the new version 4.0.0.2. Using Firefox 68.0.1 (64-bits) with Windows 10 Pro version 1903.
All groups are there, but no tabs.  I can restore the tabs from the backup, but as soon as I close and restart Firefox all groups are empty.

**Comment by Drive4ik** [comment] 2019-08-09 16:38
@m-colombo 
In version 4, the connection between groups and tabs is preserved in the session, so when updating, I asked to enable session recovery in the browser settings. This provides greater speed, and the impossibility of a huge number of bugs.
Nevertheless, I made it possible to restore tabs when closing one browser window, provided that there are 2. If there are 2 browser windows and one of them is closed, its tabs from it are created in the other remaining window.
But since you say you can close all windows on mac but without closing the browser itself - accordingly all tabs are closed and no longer be contained in groups. But instead of creating a new window, you can restore the old one from the session using the keyboard shortcut `Ctrl+Shift+N` or `Command+Shift+N` or restore window from menu history.

@Reiseend Do you enable `Restore prev session` in browser options?

**Comment by Reiseend** [comment] 2019-08-09 17:58
@Drive4ik thank you for your reply. I have my restore enabled. please refer to screenshot attached.
![2019-08-09 19_56_46-Opties](https://user-images.githubusercontent.com/53947444/62799028-03c20b80-bae0-11e9-8f74-9f0b2baedcd8.png)

**Comment by LiCybora** [comment] 2019-08-09 18:44
I can reproduce the issue on any OS.

STR:
1. Uncheck `Open "Manage Groups" in new tab`. (optional)
2. Open any extension popup tab in new window, or just the `Manage Groups` is first step is done.
3. Close all windows except the extension window. This will enter the state with no tabs and windows but still keeping Firefox main and extension processes just as the macOS case.
4. Open a new window, and you will wonder the extension icon has no color and all tabs gone.
(Up to here is your last chance to save your group by pressing `Ctrl+Shift+N` or `Command+Shift+N`)
5. Quit/close all window/kill process, whatever you like, restart Firefox.
6. All groups become empty.
7. `Ctrl+Shift+N` or `Command+Shift+N` may restore session, but tabs will not distributed back to their corresponding group - No chance to restore groups anymore.

This is likely happen when you open some other addon(s)' and using their separate window. When user click the cross for closing browser but forgot to close all addon window first, then they may get into trouble.

Workaround: NEVER close the window with red cross. Use Quit Firefox instead when closing the browser, which force all windows gone and ensure browser session.

**Comment by Reiseend** [comment] 2019-08-10 14:06
As I understand  your remark:  I should close Firefox via the dropdown 
menu:

This does not resolve the problem for me. It still does not remember my 
tabs, just the groups.

Sorry.

Op 9-8-2019 om 20:44 schreef LiCybora:

**Comment by Drive4ik** [comment] 2019-08-12 14:20
@Reiseend Are the tabs themselves in the panel restored when you open the browser?
Or out of neither in groups nor in the tab bar?

**Comment by m-colombo** [comment] 2019-08-12 14:22
> @m-colombo
> In version 4, the connection between groups and tabs is preserved in the session, so when updating, I asked to enable session recovery in the browser settings. This provides greater speed, and the impossibility of a huge number of bugs.
> Nevertheless, I made it possible to restore tabs when closing one browser window, provided that there are 2. If there are 2 browser windows and one of them is closed, its tabs from it are created in the other remaining window.
> But since you say you can close all windows on mac but without closing the browser itself - accordingly all tabs are closed and no longer be contained in groups. But instead of creating a new window, you can restore the old one from the session using the keyboard shortcut `Ctrl+Shift+N` or `Command+Shift+N` or restore window from menu history.
> 
> @Reiseend Do you enable `Restore prev session` in browser options?

@Drive4ik thank you for your reply, although the workaround works I still see this as a bug. Also quite annoying since closing all the windows (and not the process) is part of my usual workflows, and every now so often I have to restore groups, since I forgot about the issue 😅

**Comment by bloodmandarin** [comment] 2019-08-16 10:50
I have the problem, too. Firefox says "We have encountered an issue with the browser" and upon "refresh browser from last session", only the previously active group gets restored. All other groups are emptied.

**Comment by MichalBryxi** [comment] 2020-01-29 09:33
+1 with @m-colombo on this one. I **love** this extension. But there were quite a lot of occasions when I lost the tabs. I _think_ most of the time because I simply close the window.
In my mind every window simply has active a group. A group is independent on browser / window / anything. I can add / remove tabs to group by opening the group in current window and then adding / removing tabs. Or via the manage groups menu.
But the action of closing a window is merely just closing a "view" on that group.
If this could be achieved (and I could be of any assistance for it), I would be happy to see it.

**Comment by m60freeman** [comment] 2020-02-16 21:53
Every time I close FF, whether by restarting Windows or clicking on the X in the upper-right corner, I have the same result when I next start FF: Pinned tabs are there, nothing else is open, and all my STG groups exist but are empty. When I restore from the latest STG backup, all the empty groups remain and must be manually deleted before I am back to my previous state. I only ever use one FF window.

**Comment by mainmachine** [comment] 2020-02-20 21:15
@m60freeman - as discussed earlier in this thread, the current state of the add on requires that you exit FF using the "Quit" from the menu (or CTRL-Q). Closing it by any other means appears to be likely to cause various issues related to disappearing tabs.

**Comment by m60freeman** [comment] 2020-02-21 03:27
@ mainmachine I'll try to keep that in mind. Should I check or uncheck FF's "Restore previous session" setting?

**Comment by Drive4ik** [comment] 2020-02-24 17:27
@m60freeman Hi! You need to enable checkbox "Restore previous session" . Because the addon no longer stores the tabs in its memory (unless the group is archived, this will be in version 4.4). The tabs are saved in the browser session.

**Comment by Drive4ik** [comment] 2020-02-24 17:29
@m-colombo Hi! Please wait next release (4.4 or above) and try to retest your issue.
But I make no guarantee that my detour will always work well.

**Comment by m-colombo** [comment] 2020-02-25 11:18
Look like 4.4.2 solved the issue, thanks :)
Guess you can close this 👍

**Comment by Drive4ik** [comment] 2020-02-25 12:35
@m-colombo Hi! I'm glad I did it, but in any case it's better not to do it, because there may be other factors that prevent the creation or restoration of closed tabs. 
:)

**Closed by Drive4ik** 2020-02-25 12:35 UTC

**Comment by grahamperrin** [comment] 2021-02-25 08:38
## All groups emptied once closed all windows

For those of you who encounter this symptom as a result of the design of Firefox – closing **without quitting**: 

* the workaround under https://github.com/Drive4ik/simple-tab-groups/issues/716#issuecomment-785504666 may be of interest.

**Comment by grahamperrin** [comment] 2021-02-25 08:52
### Retrospective

From https://github.com/Drive4ik/simple-tab-groups/issues/434#issuecomment-590817512 above: 

> Look like 4.4.2 solved the issue, thanks :) …

----

https://addons.mozilla.org/addon/simple-tab-groups/versions/4.4.2.5/updateinfo/ lists changes in `4.4` and mentions _hotfixes_ in `4.4.2.5`, but there's no detail of what was in `4.4.2`; I assume that `4.4.2` was ultimately not release quality. 

Re: https://addons.mozilla.org/addon/simple-tab-groups/versions/ with `4.3.6.2` on 2019-12-04 then `4.4.2.5` on 2020-02-27 I find these two points for the beginning and end of a range: 

1. https://github.com/Drive4ik/simple-tab-groups/commit/4cd553f437a5eab250586e7f7122761374d0bc86#diff-945f6bf6df232d31a639475639488450ba15e360ea86d2a123f7c2f361cbf09fR13
2. https://github.com/Drive4ik/simple-tab-groups/commit/dc7c17187881397058ae8fb3b814f0bc2159a7f1#diff-945f6bf6df232d31a639475639488450ba15e360ea86d2a123f7c2f361cbf09fR13

The range: 

* https://github.com/Drive4ik/simple-tab-groups/compare/4cd553f437a5eab250586e7f7122761374d0bc86...dc7c17187881397058ae8fb3b814f0bc2159a7f1

– with this commit, first tagged `v4.4`: 

https://github.com/Drive4ik/simple-tab-groups/commit/0f9e1850480ed7011ad88dee87be8a0419b34fc5

> **try restore tabs after close window, small fixes**
