### ISSUE TITLE
Tabs are wiped if a normal window is closed and then opened after a private window is launched

### ISSUE THREAD

**Issue by Blitzkowicz** [Drive4ik/simple-tab-groups#836] opened 2021-07-01 08:58 UTC
**Describe the bug**
When a normal (non-private) firefox window, with STG on, is open, and a private window is launched, closing the normal window and opening another normal instance while the private windows is running will cause all of the tabs contained in the tab groups to disappear. All of the tab groups remain, but the only way I've been able to recover the tabs they contained is to restore from backup.

**To Reproduce**
1. Open a normal firefox window with your tab groups and tabs loaded.
2. Open a private window
3. Close the normal window
4. Open another normal window

**Expected behavior**
The tabs contained in the tab groups should not disappear.

**Screenshots**
Video of the problem:
https://user-images.githubusercontent.com/83314942/124095963-2937c580-da28-11eb-8a42-4a88224feb81.mp4

**Desktop:**
 - OS and version: Windows Version 10.0.19043 Build 19043
 - Firefox version: 89.0.2
 - Simple Tab Groups version: 4.7

**Additional context**

I forgot to record it, but the closed tabs do not appear under the "show other tabs" drop down menu in the STG interface.
The problem is reproducible regardless of whether or not STG is allowed to run in private mode.
I have no idea if this is even a fixable problem but I just wanted to bring it to your attention.

**Comment by grahamperrin** [comment] 2021-07-03 18:14
Is this a duplicate of #767?

**Comment by coaster3000** [comment] 2021-10-30 14:45
I have a feeling this issue extends past private window usage. I had to disable the addon because I am regularly losing tab group assignments and they become completely hidden unless I open up the addon's manager page.

**Closed** 2021-11-19 15:53 UTC

**Comment by nozwock** [comment] 2023-09-04 17:45
This is still happening for me, tabs from all the groups started spawning into some tab group after I clicked on `Open a New Window` while I was in a Private Window. The STG extension icon was disabled with a loading spinner, I had to wait for all the tabs to load, only then I could move to a particular tab group.

**Comment by grottas** [comment] 2023-10-03 23:00
This still happening. @Drive4ik 

Steps to reproduce: same steps as described by @Blitzkowicz and here: #767 by @arbitar

    OS and version: Windows 11
    Firefox version: 118.0.1
    Simple Tab Groups version: 5.2

**Comment by KyleWAJohnston** [comment] 2025-04-13 18:30
I'm not sure if this is the same issue, but when I close firefox, a tabs randomly get unassigned from groups and added to an ungrouped group. It's extremely annoying to have to re-organise everything after I already have several times.
