### ISSUE TITLE
STG broken on Firefox 71

### ISSUE THREAD

**Issue by grdryn** [Drive4ik/simple-tab-groups#501] opened 2019-12-04 10:27 UTC
**Describe the bug**
I upgraded to Firefox 71 on Fedora, and the extension stopped working once I restarted into the new version

**To Reproduce**
1. Upgrade to Firefox 71

**Expected behavior**
Everything works as normal

**Desktop (please complete the following information):**
 - OS and version: Fedora 31 Silverblue
 - Firefox version: 71 (RPM: firefox-71.0-8.npgo.fc31.x86_64)
 - Simple Tab Groups version: 4.3.6.1

**Additional context**
This isn't the only extension that broke. It's possible that it's an issue with the latest Fedora build of Firefox, not sure.

**Comment by Drive4ik** [comment] 2019-12-04 18:34
Duplicate of #500

**Closed by Drive4ik** 2019-12-04 18:34 UTC
