### ISSUE TITLE
Can it cause the firefox downloads toolbar button to pop open?

### ISSUE THREAD

**Issue by L-hoss** [Drive4ik/simple-tab-groups#950] opened 2022-05-16 15:43 UTC
windows 10 firefox 99, 100, at least.
A month or two ago I found firefox started popping open the toolbar downloads dropdown list at intervals. Nothing new is ever listed in the dropdown list. I found this extension is the only one I have installed that uses the "Download files and read and modify the browser’s download history" permission so wanted to ask if it's possible that this ext might be causing this behavior.
To test I'd like to disable simple tab groups. That will preserve the data, I hope?
Thanks for this incredibly useful extension. And all the best wishes to Ukraine.

**Comment by L-hoss** [comment] 2022-05-18 16:26
I found out that the dropdown list pops open whenever the automatic backup of simple tab groups takes place. So it is a bug.

**Comment by L-hoss** [comment] 2022-05-18 17:11
Oh, thank you for the heads up on this.

**Comment by nekohayo** [comment] 2022-05-23 15:08
@L-hoss please close your ticket (as it is a duplicate of 939), to keep the bug tracker better organised.

**Closed** 2022-05-23 15:34 UTC
