### ISSUE TITLE
Tab group label alongside navigation bar button

### ISSUE THREAD

**Issue by inspector71** [Drive4ik/simple-tab-groups#319] opened 2019-01-23 04:59 UTC
**Is your feature request related to a problem? Please describe.**

In Panorama-based tag groups, I was able to know which group I'm in via a text label on the navigation bar group switcher button.

**Describe the solution you'd like**

Alongside the icon, it would be very helpful to allow the button to include a text label containing the current active tab group name. 

**Describe alternatives you've considered**

The name appears on hover in a tooltip but this denies the at-a-glance efficiency that would be available with a constantly visible label.

**Additional context**

https://i.imgur.com/pXq3lsV.png (Tab Groups 2.1.4 in Firefox 52 ESR)

**Comment by Drive4ik** [comment] 2019-01-23 15:00
duplicate of #10 
But in next release will available new option, see #304

**Closed by Drive4ik** 2019-01-23 15:00 UTC

**Comment by nekohayo** [comment] 2019-06-08 20:49
Actually not a duplicate, UX-wise... the solution you implemented in #304 as a potential fix for #10 only works for users who have a titlebar above the tabs; many do not anymore...

I suspect the Web Extensions API does not allow putting widgets all over the place such as "next to the tabs", but maybe it still allows putting something in the URL bar? For example, Firefox's built-in containers feature shows the container's name (and color) inside the addressbar on the right... if so, it could be worth reopening this ticket.

**Comment by Drive4ik** [comment] 2019-08-13 09:00
@nekohayo I already tested this idea, and nothing came of it. Mozilla add-ons have more privileges than any other extensions ... I even thought of generating a 16x16 picture with the name of the current group :) But this is a bad idea .. maybe in the future they will add such functionality to all other extensions ...

**Comment by grahamperrin** [comment] 2020-03-21 11:26
Yeah, the constraints of WebExtensions APIs are unfortunate. 

I do miss the menu button of Tab Groups. 

Ideal UX. The name of the group – in this example, _Waterfox_: 

![image](https://user-images.githubusercontent.com/192271/77225389-98a4e100-6b66-11ea-8ef5-f5e62f7a9c40.png)

* where required
* on the button
* at the head of the menu.

**Comment by Drive4ik** [comment] 2020-03-21 13:24
I got a very stupid idea, but it will solve this problem 😄 
In general, make a folder with bookmarks, and the name of this folder - this will be the current group. The bookmark folder will be located on the topbar, and there will be groups in it in the form of bookmarks. When you click on a group (bookmark), a new tab will be created with a special URL that will switch the group. And then this tab will be deleted as unnecessary. You will only need to set the parameter `browser.tabs.loadBookmarksInTabs` set to `true`
It will look something like this:
![изображение](https://user-images.githubusercontent.com/7843031/77227205-2b557800-6b87-11ea-9bea-59c732645200.png)

Guys, how do you like mocking FF? 😄 
P.S. The idea is feasible, but may not be very stable in operation, for example, if you click "Open All in Tabs".

**Comment by grahamperrin** [comment] 2020-03-22 04:58
@Drive4ik thanks, after discovering the sidebar I'm happy. 

## Use case

FreeBSD-CURRENT. 

The sidebar of Simple Tab Groups – 

![2020-03-22 04:04:37](https://user-images.githubusercontent.com/192271/77242181-92107b00-6bf3-11ea-9e4b-1272344c63fb.png)

– is a neat complement to a KDE Plasma panel, far left, that includes the task manager. 

I have a shed load of extensions, with my bookmarks in the menu bar (so the bookmarks toolbar can be used for extensions): 

![2020-03-22 03:13:04](https://user-images.githubusercontent.com/192271/77242397-d13fcb80-6bf5-11ea-99e9-5d9a78544c5c.png)

Now, just a few special extensions in the main toolbar (accessible in full screen mode), with some custom shortcuts. 

### A quartet

**[Saka](https://addons.mozilla.org/addon/saka/)** – <kbd>Alt</kbd>-<kbd>Space</kbd>

![2020-03-22 03:15:39](https://user-images.githubusercontent.com/192271/77242465-8d999180-6bf6-11ea-90c2-9350f14f890b.png)

**[Simple Tab Groups](https://addons.mozilla.org/addon/simple-tab-groups/)** pop-up – <kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>Space</kbd>

![2020-03-22 03:15:50](https://user-images.githubusercontent.com/192271/77242526-2cbe8900-6bf7-11ea-8d5d-af61d6e0ed94.png)

**[Tabs2List](https://addons.mozilla.org/addon/tabs-2-list/)**

![2020-03-22 03:16:02](https://user-images.githubusercontent.com/192271/77242562-9b034b80-6bf7-11ea-979b-3d0c25277165.png)

**[Tab Manager Plus](https://addons.mozilla.org/addon/tab-manager-plus-for-firefox/)**

![2020-03-22 03:16:35](https://user-images.githubusercontent.com/192271/77242586-e74e8b80-6bf7-11ea-9ec8-72ab2b0e0fbb.png)

### Sidebar shortcuts

I chose: 

* <kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>G</kbd> for Simple Tab Groups
* <kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>T</kbd> for @piroor [Tree Style Tab](https://addons.mozilla.org/addon/tree-style-tab/), which I [keep flat](https://github.com/piroor/treestyletab/issues/2494) (for grouping, I prefer Simple Tab Groups).
