### ISSUE TITLE
Supporting Firefox ESR

### ISSUE THREAD

**Issue by Roebie** [Drive4ik/simple-tab-groups#205] opened 2018-07-07 12:03 UTC
This add-on requires a newer version of Firefox (at least version 61.0). You are using Firefox 60.0.

Is it really necessary to have at least version 61.0?
Lowering the requirements to 60.0 would make the add-on also compatible with Firefox ESR.

**Comment by gagarine** [comment] 2018-07-07 12:55
Yes it's necessary. This add-on is based on a new API (tab hidden) that is not available before.
The old version of this addon was using some kind of "hack", those old version should work on ESR.

**Comment by LiCybora** [comment] 2018-07-07 14:38
I don't think ESR will change default config, as ESR only receive security updates. If you really need to use this extension in Firefox ESR 60, you may consider build it yourself.
 - Mod this file: ` simple-tab-groups/addon/src/manifest.json`
 - Then go line 7: ` "strict_min_version": "61.0"`, change to `60.0` will work
 -  Follow the build instructions in README.MD to build it yourself.

ESR allow you install unsigned extension by editing `xpinstall.signatures.required` to `false` in `about:config`, so you can just drag-and-drop the built zip file to `about:addons` page to install.

But I can tell there may be regression problems in Firefox 60 ESR, at least on macOS due to a browser bug (fixed in 61). And also you **MUST** turn on `extensions.webextensions.tabhide.enabled` in `about:config` manually. These reasons cause 61 is required.

**Comment by Drive4ik** [comment] 2018-07-09 14:39
@LiCybora Yes, you are right. But I do not vouch for the correctness of the work, because in FF 61 were fixed bugs that are critical for Simple Tab Groups. Here is one of them
https://bugzilla.mozilla.org/show_bug.cgi?id=1398272
in this bug fixed bug when you transfer a tab from one window to another by Drag&Drop.
This can lead to data loss...

@Roebie 
If you realy want - here is an addon for testing.
**But you do everything at your own peril and risk!**

[simple_tab_groups_esr-3.0.9.zip](https://github.com/Drive4ik/simple-tab-groups/files/2176603/simple_tab_groups_esr-3.0.9.zip)

before install you need change file name from
`simple_tab_groups_esr-3.0.9.zip`
to
`simple_tab_groups_esr-3.0.9.xpi`

and you must do only this:

> turn on extensions.webextensions.tabhide.enabled in about:config manually.

> so you can just drag-and-drop the built zip file to about:addons page to install

or click here on `about:addons` page
![default](https://user-images.githubusercontent.com/7843031/42456901-ad7080c8-839e-11e8-866a-fce477d21397.png)
and select this file

**Comment by Drive4ik** [comment] 2018-07-09 14:43
P.S. after 2019-07-09 you need to create backup in STG, disable it and import into global STG which will in Firefox ESR 68.0 on 2019-07-09 :)

https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates

**Comment by adipose** [comment] 2018-07-27 16:42
I wonder if bug fixes are ever backported to ESRs?

**Comment by Drive4ik** [comment] 2018-10-25 14:20
@adipose STG now not support ESR branch and will not support anytime soon, does not have much functionality..

**Closed by Drive4ik** 2018-10-25 14:20 UTC
