### ISSUE TITLE
Group doesn't synchronize with the add-on

### ISSUE THREAD

**Issue by crumbleRhubarbe** [Drive4ik/simple-tab-groups#50] opened 2018-01-21 09:05 UTC
Hi,

Sometimes when i startup Firefox, the tabs I opened in a group don't sync with the add-on. If I change group I then loose all of them.

You can see on the pictures below that 1. the simple-tab-groups icon doesn't show any color on the bottom left corner and 2. there is more than 5 tab in the window but only 5 shown in the dev group, the one that should be selected.

I don't know yet how to reproduce this, I'll try to track down why. Tell me if you need me to provide you other files.

![group not found](https://user-images.githubusercontent.com/621850/35192423-3894d736-fe92-11e7-8c85-f58ee6d73500.PNG)

![group not sync](https://user-images.githubusercontent.com/621850/35192424-38c79fd6-fe92-11e7-81ff-720ecd925bf1.PNG)

**Comment by SladeThe** [comment] 2018-01-23 16:52
I can confirm this issue.

Also when the number of tabs shown differs from the real number of tabs, there is one additional effect. If you move a tab from such group to another group, it appears in the target group, but is not removed from the source group. Instead some other tab may disappear from the source group. Probably the tabs are referenced by some sort of indices and not by the unique ID.

**Comment by Drive4ik** [comment] 2018-01-24 18:48
Please, retest this issue with latest addon version (2.3.1)

**Comment by Drive4ik** [comment] 2018-01-29 16:27
Please, re-test this issue in latest version v2.3.5

**Comment by Drive4ik** [comment] 2018-02-08 14:23
Tabs will not be updated unless the group has been synchronized

**Comment by Drive4ik** [comment] 2018-02-09 18:04
Hi all!
Can you update to v2.4.1 and retest again?
I find some strange behavior and try to fix this issue.

**Comment by Speravir** [comment] 2018-02-11 14:53
Doesn’t work with version 2.4.1, too. It worked here with version 2.3.6, if I remember correctly. I wanted to check this before posting, but installation of this older version was denied. _(What the … It is absolutely OK to notify about a new version, but it should be my own decision to install an older version.)_ With v. 2.4.1 on every start I get a notification “No one group was not synchronized! Please, select group to sync tabs”

I wouldn’t even mind this if I hadn’t activated the setting for opening a new window for every group. This new window is slightly shifted to the right. And the annoying part here is: On next browser start I would start at this shifted position, and after a couple of starts the browser starts on the very right of the desktop. I didn’t check what happens if the window touches the right desktop edge, whether it eventually would move to the very left.

**Comment by Drive4ik** [comment] 2018-02-12 15:50
Hello!
I think I found the problem. it turned out this is not the clean-up behavior of firefox. eg
you have a synchronized group that has 3 tabs

- tab1
  - active: false
  - status: complete
  - url: URL_1

- tab2
  - active: true
  - status: complete
  - url: URL_2

- tab3
  - active: false
  - status: complete
  - url: URL_3

-------
but, if restart FF and on startup call "function get tabs" it returns there:
- tab1
  - active: false
  - status: complete
  - url: URL_1

- tab2
  - active: true
  - status: loading
  - url: about:blank (and at that moment load URL_2)

- tab3
  - active: false
  - status: complete
  - url: URL_3

sorry for my English))

this fix will be in next version 2.4.2

**Comment by Drive4ik** [comment] 2018-02-12 16:21
New version released, please re-test this behavior.

**Comment by Speravir** [comment] 2018-02-12 19:04
Yes, works. Great! Before someone complains: It did _not_ on first ~~reload~~ restart after regular closing, but fine from the second (I intentionally tested several times). Maybe some cached script content?

**Comment by Drive4ik** [comment] 2018-02-13 16:44
Maybe cache, maybe FF.. Quantum is not very stable now..
Please, close issue if you have no questions

**Comment by Speravir** [comment] 2018-02-15 16:18
Some days later I must say I does not work on every first start after restart of computer, so that’s still not the best situation. Do your addon use local storage or indexed DB or so? Because I also use the addon [Forget Me Not](https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/) which deletes these. there are settings for it, but I do not see, how they should be for Simple Tab Groups and how to apply for it. I also do not know which of the addons needed an update regarding this.

**Comment by Speravir** [comment] 2018-02-15 17:04
Some days later I must say I does not work on every first start after restart of computer, so that’s still not the best situation. Do your addon use local storage or indexed DB or so? Because I also use the addon [Forget Me Not](https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/) which deletes these. there are settings for it, but I do not see, how they should be for Simple Tab Groups and how to apply for it. I also do not know which of the addons needed an update regarding this.

_Update:_ Oh, perhaps even more important is that I also use the [Tab Session Manager](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/).

**Comment by Drive4ik** [comment] 2018-02-15 17:25
but now you do not have this problem?

**Comment by Speravir** [comment] 2018-02-16 16:28
> Maybe you forgot sync group with window and restart browser (for the first time)?

How could I forget or: Where is such a setting to set it on or off?

>but now you do not have this problem?

Oh, I have. Also today.

Some background: In my tests mentioned some days ago I closed Firefox, but started after some seconds when all processes in background had been closed (otherwise Firefox would have complained about the older open process), and it worked – not just once, but several times what I wrote here.  
But every day I close my computer in oldschool style with a real shutdown, not with hibernating. And on the next day on every first start the tab groups cannot be opened. I probably should make a test with closing Firefox for minutes, but I use it too much. Forget Me Not has a setting for deleting everything (can be configured) on browser start, but this should, of course, also executed when I close the process(es) for seconds only. My second thought the issue could be related to Tab Session Manager, has the same rub.

**Comment by Speravir** [comment] 2018-02-17 18:31
Next day, self cite:
> Ehm, do you mean the general Firefox setting for syncing tabs outside your addon settings?

No, I have activated this, but the behaviour did not change.

**Comment by Tamehome** [comment] 2018-03-10 16:21
I'm using v.2.4.7.
This is what I've observed when FF restarts.
After a normal FF exit and restart:
- Window 1 Synchronized tab list loads.  The session history is also maintained, which is great.
- Window 2+ Normal session restoration, but tab synchronization is not enabled.  Opening a Synchronized tab group loses the session history for the restored tabs.
- - After first installing v2.4.7, restarting FF normally caused all Windows to load the synchronized tab lists.  Ever since then, only Window 1 loads the synchronized tab list.

After FF termination (e.g., OS reboot), then FF restart:
- Normal session restoration.
- No Windows have synchronized tab lists enabled.

If all of the Windows can have the synchronized tab lists enabled during normal restart or termination + restart, that would be great.

**Comment by Drive4ik** [comment] 2018-03-21 16:49
Hi! Can you retest this bug in latest version? (v2.5)
If bug was fixed - close issue.

Thanks

**Comment by Tamehome** [comment] 2018-03-26 11:17
Hi, I just tested with v2.5.3, and after closing and opening FFX a few times, it does appear that the synced sessions are getting restored.  Only 2 remaining issues so far.
1. When a synchronized window is opened, there is often 1 blank tab opened at the end.  This didn't happen with v2.4.7.  I disabled the other tab plugins, but the tab still appears.
2. While normally closing and opening FFX does appear to work correctly, terminating FFX and reopening it, or if the computer crashes, doesn't appear to resync all the tabs.  Only the first tab got resynced.

**Comment by Drive4ik** [comment] 2018-03-26 11:52
@Tamehome 

1. If you just open and close the browser - then this should not happen. Addon does not create or close tabs at startup.
2. When FF was craches - it is difficult to foresee something and fix it. There are many such situations.

What are your settings in the addon?

**Closed by Drive4ik** 2018-03-26 11:52 UTC
