### ISSUE TITLE
Donations 

### ISSUE THREAD

**Issue by bjoernbuth** [Drive4ik/simple-tab-groups#789] opened 2021-03-10 19:29 UTC
Hi, I'm sorry if "issues" might be the wrong place. 
Just wanted to let the creator of simple-tab-groups know 
that I'm very impressed and satisfied with this add-on. 
I'd surely donate (wouldn't be much but something in the
5$ range) if there is a method given. 

I didn't find an Email adress or other means to contact, so
I apologize if this might be the wrong way to suggest donations.

**Comment by grahamperrin** [comment] 2021-03-18 01:24
@bjoernbuth thanks, would you like to close this issue? It's largely a duplicate of #120

**Comment by bjoernbuth** [comment] 2021-03-19 01:16
sure, thanks for the clarifaction.

**Closed** 2021-03-19 01:18 UTC
