### ISSUE TITLE
Possibility to add folders

### ISSUE THREAD

**Issue by mtnjustme** [Drive4ik/simple-tab-groups#586] opened 2020-04-12 15:21 UTC
**Is your feature request related to a problem? Please describe.**
none
**Describe the solution you'd like**
make folders that contain groups inside (for example, a folder named videos, and inside "Twitch" and "Youtube" groups), this would make my extension personally more useful, and i guess would help others as well (it's only lookwise, won't change the extension functions themselves, groups are still the same, just the ability to add folders in order to make it more comfortable, option to add a folder and option to add a group, and simple move groups to the specific fitting folder).
**Describe alternatives you've considered**
none
**Additional context**
none

**Comment by mtnjustme** [comment] 2020-04-12 15:32
another important thing :
i also can figure nested folders can be a problem, so making it only 1 folder level would be useful as well.

**Comment by Drive4ik** [comment] 2020-05-05 14:09
Duplicate of #302

**Closed by Drive4ik** 2020-05-05 14:09 UTC
