### ISSUE TITLE
Backup folder location should not be on the desktop, and/or should be customizable

### ISSUE THREAD

**Issue by knezmilos13** [Drive4ik/simple-tab-groups#1005] opened 2023-01-19 07:48 UTC
Apparently backup is done to a folder on the DESKTOP. This is an amazingly terrible choice of location. I just cannot imagine how someone could have been like "Yeah, let's have it there by default, I'm sure most people want to see a random backup of a random plugin right in the middle of their desktop every day".

Anyway, in the settings I tried changing the backup folder name to:
C:\Program Files\Mozilla Firefox\STG-backups-FF-109.0

But it just ends up creating a folder on the desktop named:
CProgram FilesMozilla FirefoxSTG-backups-FF-109.0

Edit: my system is Windows 10 Pro, FF 109.0, and plugin version 4.7.2.1

**Comment by achernyakevich-sc** [comment] 2023-01-19 09:57
I had seen similar situation when backup folder was created in quit strange location - `Downloads`. I have suspicion that for some reason backup folder is created inside the folder where Firefox installation file was run from. But it is more like a hypothesis.

@knezmilos13 Have you run Firefox installation file from `Desktop`?

**Comment by knezmilos13** [comment] 2023-01-19 13:10
Most likely I have, I do usually download stuff to desktop. Although can't say for sure since FF is probably the first thing (and only thing) I downloaded by using Edge, and I wouldn't have wasted time configuring it, so Edge's default download location could have been elsewhere.

**Comment by sbirl** [comment] 2023-02-07 13:37
Yes, I have to agree to this request -- especially since I have multiple FF profiles that run STG.  _I would think that the default dumping ground would be a folder within the profile folder itself._

**Comment by nekohayo** [comment] 2023-02-09 04:29
It's an API limitation and there is no known possible fix for this so far. Please close your issue as a duplicate of #778.

**Comment by jelias** [comment] 2023-02-13 19:55
There is a known possible fix, it has been mentioned in both #778 and #977, but rather than try to leverage the storage api, you just push to close these issues... why? Rather than closing all of the duplicates and burying the problem (because someone will just open another issue), perhaps, re-open the original issue and .

Every other extension does not write to the Desktop folder but instead properly uses the `storage`api provided to save extension data to the user profile.

**Comment by Drive4ik** [comment] 2023-04-08 15:07
@jelias @knezmilos13 
That's the point. Sometimes, and sometimes very part of Firefox crashes, and you lose your whole profile. Including bookmarks, passwords and addon settings that save data in the profile using the `storage` API. 
If you don't like the location of your browser's downloads folder, change it! Browser settings:
![изображение](https://user-images.githubusercontent.com/7843031/230728297-a901b58c-3f5f-463d-89f5-e8ffd4196683.png)


Or you can disable the backup at all:
![изображение](https://user-images.githubusercontent.com/7843031/230728496-a4df504f-0385-4ab6-983b-07d282ebbaf8.png)

**Closed by Drive4ik** 2023-04-08 15:07 UTC

**Comment by tobiasdiez** [comment] 2023-05-06 16:04
@Drive4ik but if I would like to prevent such data loss, I would of course make a backup of the local profile folder, or not? But with simple-tab-groups I now also need to backup a folder under downloads.

Would it be possible to provide the option to backup to the local profile, and then inform the user about possible inconveniences of both methods?

**Comment by achernyakevich-sc** [comment] 2023-05-08 08:55
> but if I would like to prevent such data loss, I would of course make a backup of the local profile folder, or not? But with simple-tab-groups I now also need to backup a folder under downloads.

@tobiasdiez I have a workaround for you. STG create backups in the folder that Firefox was installed from. Temporary disable automatic update of Firefox. So you could download next Firefox update installation file and place it to the folder where you would like to have backups in. Then run installation file and reinstall Firefox (as I know your profile will be kept untouched). After that STG will create backups in and you ca enable automatic updates again. :)

**Comment by Drive4ik** [comment] 2023-05-09 11:58
There is another workaround: create a symlink to the backup folder in the downloads folder, and place the backup folder anywhere you want. The `Link Shell Extension` will help
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

#778 #977
