### ISSUE TITLE
[Feature request] Provide an additional way to switch between the groups

### ISSUE THREAD

**Issue by Git-GT** [Drive4ik/simple-tab-groups#966] opened 2022-07-20 19:21 UTC
**Is your feature request related to a problem? Please describe.**
Having only a button to switch between groups slows down the workflow as you have to click on the button, and then on the tab group. Furthermore, with only the button, it is not immediate to understand at first glance on which group you are and how many groups there are.

**Describe the solution you'd like**
It would be nice to have an additional tab bar, on top of the standard one, that refers to the groups.
Also, would be nice to highlight the tabs of a certain group using a the group color on as their background or tab border.

**Describe alternatives you've considered**
Instead of the additional tab bar it could be implemented using a buttons bar on which each button corresponds to a group and is identified by the icon on the left and the name on the right.

**Comment by unikitty37** [comment] 2022-08-10 08:34
I'd like to have the option to have expanding/collapsing groups in the main tab bar, too, like Vivaldi:

![image](https://user-images.githubusercontent.com/139183/183854454-ba037983-5db5-4dd1-b7eb-4036164ce8af.png)

(blue group highlight is added with custom CSS as the default theme doesn't really distinguish between them)

Clicking on a group expands it; the toggle buttons expand/collapse it, and there's an option to have groups auto-collapse when the active tab isn't part of them.

**Comment by NicoForce** [comment] 2022-08-14 23:47
@unikitty37 You should probably create that one in a separate issue, although that probably is not possible atm due to the current api.

**Comment by nekohayo** [comment] 2022-10-01 13:45
> Having only a button to switch between groups slows down the workflow as you have to click on the button, and then on the tab group.

I use the `F8` keyboard shortcut to easily/quickly access this. There is also the sidebar functionality that you can use.

> Furthermore, with only the button, it is not immediate to understand at first glance on which group you are and how many groups there are.

This is essentially a duplicate of issues #319 and #10, and there's nothing that can be done (as far as I know) with the limitations of the WebExtensions API.

> It would be nice to have an additional tab bar, on top of the standard one, that refers to the groups.
> Also, would be nice to highlight the tabs of a certain group using a the group color on as their background or tab border.

I am guessing, but reasonably certain, that none of this can be done with the WebExtensions API.

As such, overall I think there is nothing more Simple Tab Groups can do here, and no actionable outcome, so I would recommend closing this ticket to keep the bug tracker clean.

**Comment by Drive4ik** [comment] 2023-03-01 00:35
This cannot be done, due to limitations of the WebExtensions API

**Closed by Drive4ik** 2023-03-01 00:35 UTC
