### ISSUE TITLE
Data corruption

### ISSUE THREAD

**Issue by YoniGTA** [Drive4ik/simple-tab-groups#1203] opened 2024-09-24 11:10 UTC
**Describe the bug**
The tab group data appears to be corrupted.

**To Reproduce**
I did nothing unusual.

**Expected behavior**

**Screenshots**
<img width="788" alt="Data corruption" src="https://github.com/user-attachments/assets/f4951501-cc8a-4964-90d0-a8394518679f">

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 130.0.1 (64-bit)
 - Simple Tab Groups version: 5.2

**Additional context**
STG reported an error, but I didn't act on that.
The corruption I'm reporting is the text that appears at the start of each line in the screenshot:
@1:#n
or
@no window:#n

Other backups have the same problem. STG seems to be working.
What should I do?

**Comment by YoniGTA** [comment] 2024-09-24 11:14
The corruption I'm reporting is the text that appears at the start of each line in the screenshot:
@1:#n
or
@no window:#n

What should I do?

**Comment by achernyakevich-sc** [comment] 2024-09-24 21:24
It looks like this issue it duplicate of #1148.

Could you close this one and continue discussion in the mentioned above issue.

**Closed** 2024-09-25 09:18 UTC
