### ISSUE TITLE
The 'manage groups' button in invisible unless cursor hovering over the hidden sliver of the bar.

### ISSUE THREAD

**Issue by Philip-Sutton** [Drive4ik/simple-tab-groups#193] opened 2018-06-29 12:54 UTC
Hi,  I like the new build using 'hiding tabs' technology.

Unfortunately a previously solved problem has returned.  When in the main pop-up window, the  'manage groups' 'bar' appears to be not displayed on my machine (Windows 10, Firefox 61.0).  See the animated gif below.).   But there is a tiny sliver of the bar hidden at the bottom of the popup that will give access to the 'manage groups' button that is invisible unless cursor hovering over the hidden sliver of the bar.

Philip
 
![hidden option to access the group management page](https://user-images.githubusercontent.com/1549449/42093022-502a2e08-7bee-11e8-98b7-db30071ae41d.gif)

Philip

**Comment by Drive4ik** [comment] 2018-07-04 07:19
Hi! It seems to me or you use version 2 instead of 3? I try again to fix this bug

**Comment by Drive4ik** [comment] 2018-07-04 13:56
This is FF bug, and no matter how I tried to fix it - nothing happens ...

**Comment by Drive4ik** [comment] 2018-07-04 14:10
Duplicate of https://github.com/Drive4ik/simple-tab-groups/issues/135

**Closed by Drive4ik** 2018-07-04 14:10 UTC

**Comment by Philip-Sutton** [comment] 2018-07-04 18:15
Drive4ik- This is FF bug, and no matter how I tried to fix it - nothing happens ...
