### ISSUE TITLE
Last active tab duplicated on browser restart

### ISSUE THREAD

**Issue by me21** [Drive4ik/simple-tab-groups#295] opened 2018-11-23 08:26 UTC
**Describe the bug**
When I reopen the browser on a new day morning, the tab that was active when the browser was closed yesterday is duplicated. There are two identical tabs. 

**To Reproduce**
1. Note the active tab and close the browser.
2. Reopen it. You should have two copies of the tab now.

**Expected behavior**
Tab should not be duplicated.

**Screenshots**
I will attach screenshots after I create the issue.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 x64 LTSB
 - Firefox version: 63.0.3 x64
 - Simple Tab Groups version: 3.3.4.

**Comment by me21** [comment] 2018-11-23 08:39
Okay, I failed to reproduce the issue right away. I even tried restarting my laptop... nothing. I will watch more closely at it and I will reopen it, if it manifests itself again.

**Comment by me21** [comment] 2018-11-28 09:54
I've noticed that the browser opens without duplicated last tab while the extension is loading (it takes some time to load on my machine), but when the extension is fully loaded, the tab gets duplicated.
Hope that helps.

**Comment by Drive4ik** [comment] 2019-01-17 16:11
I know about this behavior. This happens if, for example, before closing the browser, the last active tab has a session, then after opening the browser, the tab starts loading, but since the site session is already lost, the URL on the login page for example may change, and when the addon is loaded, it does not find the old URL and creates new tab with it.
I hope clearly explained.
Translated using Google Translate :)

**Comment by me21** [comment] 2019-01-17 20:01
Er, I am sure it happens for tabs without sessions too, e.g. https://github.com/espressif/arduino-esp32/issues

**Comment by Drive4ik** [comment] 2019-01-18 11:09
Can you retest this issue with Firefox 64?
I can't reproduce the bug, I spent a lot of time on the implementation of the launch of the add-on, and I only see one option why this happens - the URL changes

**Comment by Drive4ik** [comment] 2019-01-21 18:48
just want to clarify
`https://github.com/espressif/arduino-esp32/issues/1116`
and
`https://github.com/espressif/arduino-esp32/issues/1116#issuecomment-415380962`
These are 2 different URLs for the program but one page and maybe have a place to be
![change-git-url](https://user-images.githubusercontent.com/7843031/51493293-935ed180-1dbd-11e9-8bad-28c18401a9fa.gif)

I want to say that any change in the URL of any tab before the add-on is loaded will result in the restoration of the old URL after addon load, in order to avoid data loss.

**Comment by Drive4ik** [comment] 2019-02-26 15:23
Please retest this issue on latest STG version

**Comment by grahamperrin** [comment] 2021-02-28 08:24
@me21 two years have passed with no feedback, from which I assume that there's no longer a problem.

Would you like to close this issue? Thank you.

**Closed** 2021-02-28 13:46 UTC

**Comment by grahamperrin** [comment] 2021-02-28 18:28
Thank you!
