### ISSUE TITLE
Tab ordering after switching groups

### ISSUE THREAD

**Issue by vrurg** [Drive4ik/simple-tab-groups#98] opened 2018-02-22 18:14 UTC
Not sure if it's to be considered as a bug report or feature request, but is it possible to preserve the tab ordering upon switching groups? Say, a development session quite often accompanied by 20-30 opened tabs with docs, searches, tests, etc. They're usually arranged in a way to speed up access to the information needed at every particular moment of time. But then you switch forward and back again – and everything is in perfectly chaotic mess.

I understanf that if Mozilla API doesn't provide a possibility to iterate over an order list of tabs then I would have to keep dreaming of better API. 😀

**Comment by dgutov** [comment] 2018-03-23 22:53
Can you provide a repoduction scenario? I've briefly tested two versions of this addon (one of the recent releases and the "experimental" one), and in neither did I see this problem.

**Comment by Drive4ik** [comment] 2018-03-24 00:42
@dgutov Hi. I ported this fix from experimental version to latest current stable, and its works.

**Comment by Drive4ik** [comment] 2018-03-24 00:44
Duplicate of #18 and #7

**Comment by Drive4ik** [comment] 2018-06-27 12:11
Please retest this issue on STG 3.0 and FF 61
If bug still replicate - reopen this issue if you need

**Closed by Drive4ik** 2018-06-27 12:11 UTC
Labels: Fixed, bug, duplicate

**Comment by Drive4ik** [comment] 2018-11-12 16:42
@HeRo002 Can you describe in more detail the essence of the problem, or make a gif animation?

https://www.screentogif.com/

**Comment by HeRo002** [comment] 2018-11-12 18:06
Well... I switched away from the group I use the most, and when I switched back, at least 3, probably 6, tabs had moved from the end of the list of tabs to become tab number 3 and forth. But I don't know if that helps you?

**Comment by HeRo002** [comment] 2018-11-20 18:04
Have you been able to replicate this bug?

**Comment by Drive4ik** [comment] 2019-01-18 12:01
@HeRo002 Can you disable other add-ons and try to repeat the problem several times? And if the problem will not be repeated - turn on the add-ons one at a time and check again, so you will find an addon with which there is a conflict, and it is possible to change the settings in it to fix the problem

**Comment by HeRo002** [comment] 2019-01-20 15:31
I will try to remember doing that, if I notice the problem again.
