### ISSUE TITLE
Assign a group to a container and open all tabs in it in this container by default

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#236] opened 2018-09-02 21:58 UTC
Hi 
It could be useful to assign a group to a container so that all tabs opened in this group (by link, bookmark or address bar) shall open in this container by default. Then of course we have the question about other such automations like Containerise... not sure what to do in the case. 
And if no such container is defined for a group, then the standard behaviour happens.
I noticed that this is the way I work on different topics: I have one group per topic and one container per topic actually. 
Possibly other do the same :)
Thanks 
Cheers

**Comment by GonzRon** [comment] 2019-01-22 00:14
@klint is this similar to #302?

**Comment by klint** [comment] 2019-01-22 13:03
@GonzRon While I'll find your request quite interesting, I don't think it's the same as mine :).
The request here is about links between contexts  (aka "containers" in Firefox, with context isolation) and tab groups. Yours is about groups of groups.

I take this as an opportunity to clarify some use cases:
It is today already possible to open a tab in a given context then have STG automatically move it to the right tab group, but the current request is to have it the other way as well: open a tab in a tab group and have STG open it in a given container/context.
For instance, suppose we had a group called "Banking": all tabs opened in this group could open in the "Private banking" context.

Or, even better, assume you worked for several customers, each of them having a dedicated Google account: I would create one group per customer and one container per customer. Then, opening the standard Gmail URL in "Customer A" group would use the "Customer A" container, hence the "Customer A" Google identity/account. And similarly for "Customer B", but still starting from the same Gmail URL.

**Comment by Drive4ik** [comment] 2019-01-23 15:13
duplicate of #95 
Sorry, but full functionality `A container per group` as you want, it is impossible to make without errors and lags. All that is now implemented is all that can be done at the moment...

**Closed by Drive4ik** 2019-01-23 15:13 UTC

**Comment by Drive4ik** [comment] 2019-10-11 15:59
Hi all! In latest version (v4.1) I added this option in group settings.
Please test.

**Comment by maverick74** [comment] 2019-10-11 22:12
Not able to test it ATM. Probably monday...

About the lag, I suppose there hasn't been any improvements (in Firefox, since it's were the problem is...), or have I missed something?

**Comment by Drive4ik** [comment] 2019-10-16 17:15
@maverick74 no, I took the idea from the addon `Facebook Container`:
https://addons.mozilla.org/en/firefox/addon/facebook-container/

**Comment by GonzRon** [comment] 2019-10-16 17:22
I have been testing and using this feature and it is working OK, however I did not raise it originally so maybe I don't understand the use case 100%.  It appears to work OK for me, thank you this is quite useful feature.

**Comment by Drive4ik** [comment] 2019-10-16 17:28
@GonzRon 
In general, any operations with tabs in the group in which the container is assigned..
create/delete/move tabs (including moving between two groups with containers assigned).
Something like this

**Comment by GonzRon** [comment] 2019-10-16 17:32
Very well I can try. Thank you again.
