### ISSUE TITLE
Tabs are auto-hidden at Firefox launch, annoying when opening via a URL

### ISSUE THREAD

**Issue by Acru** [Drive4ik/simple-tab-groups#468] opened 2019-09-12 22:17 UTC
Tabs opened at Firefox launch (by clicking a URL while Firefox isn't running) or tabs opened while STG is still loading are automatically hidden once STG is loaded, and the 'show other tabs' section now being folded by default in v4 makes it even harder to get them visible again!  You just loaded Firefox to view these URLs, and having them hidden right away is super annoying.

Ideally these tabs should not be hidden, but rather added to the current group and remain visible.  (One can always sort them to the right group later, assuming they are kept open after viewing.)  If not change the default behavior, could you add an option for this, please?

**Comment by Drive4ik** [comment] 2019-09-17 15:28
Hi!
Duplicate of #450
Fixed, please wait next release

**Closed by Drive4ik** 2019-09-17 15:28 UTC
