### ISSUE TITLE
[Feature Request] Ability to sync groups across machines.

### ISSUE THREAD

**Issue by punitjain8695** [Drive4ik/simple-tab-groups#593] opened 2020-04-23 18:54 UTC
**Is your feature request related to a problem? Please describe.**
Firefox does sync tabs across devices, but it doesn't sync groups. Having <10 groups open on one machine, and need to sync one group to another machine, maybe all.

**Describe the solution you'd like**
It would be really helpful if we could sync tab groups between devices. An implementation I could think of is: Backup groups of tabs to Google Drive(Basically setup google drive to pickup the STG backup file and sync to drive) . And setup tab groups to check for the same file on the other PC, and if open, we have an option to load tabs from file. 
If someone wants to have a good sync, they can do so by basically just syncing that one file using whatever software they want. 
Currently, one has to manually go to options and restore from file.What I'm asking is, for a checkbox to do that automatically, if it doesn't find a file there, restore the local version. 
Also, if it could be done for selected groups, it'll be really dope. :D
This feature might already be available, and I don't understand how to use it, maybe, if so, please let me know. 

**Describe alternatives you've considered**

Can't think of alternatives at the moment. I'll surely update if I find/think of another.

**Comment by Drive4ik** [comment] 2020-05-06 16:31
Duplicate of #291

**Comment by Drive4ik** [comment] 2020-05-06 16:31
please read https://github.com/Drive4ik/simple-tab-groups/issues/291#issuecomment-451531973

**Closed by Drive4ik** 2020-05-06 16:31 UTC

**Comment by punitjain8695** [comment] 2020-05-07 17:04
Didn't know of that restriction. Thanks :) Just checked that backup file for myself, it was around 2 MBs 🤣
